### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by idkjs** [jploskonka/testing-with-codeceptjs#1]
Add .eslintrc and/or .babelrc configurations to project.

**Comment by jploskonka** [comment]
Hey, thanks for suggestions :)

Integration with eslint is one the things I definitely need to check up with this project, probably when I start integrating Codecept with CI flow.

When it comes to `.babelrc` I'm not exactly sure why should it be added here if project does not use Babel?

**Comment by idkjs** [comment]
Then dont put it in. Just suggesting to have it the project set up from go.
